version: '3.7'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=my_database
      - MARIADB_PASSWORD=my_password

  myapp:
    tty: true
    image: docker.io/bitnami/laravel:8
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=my_user
      - DB_DATABASE=my_database
      - DB_PASSWORD=my_password
    depends_on:
      - mariadb
      - php  
    ports:
      - 8080:3000
    volumes:
      - ./laravel:/app
    # privileged: true # Privileged mode could be required to run this container under Windows
   
  php:
    image: php-xdebug-custom
    volumes:
      - ./laravel:/var/www/myapp
      - ./laravel/site.ini:/usr/local/etc/php/php.ini
